"""
Question answering using the shared AI layer.

This module automatically benefits from the Gemini -> Groq
fallback implemented inside helpers.gemini_client.generate_content().
"""

from helpers.gemini_client import generate_content


def get_answer(question: str, context: str) -> str:
    """
    Generate an answer using only the retrieved PDF context.
    """

    if not question or not question.strip():
        raise ValueError("The question cannot be empty.")

    if not context or not context.strip():
        raise ValueError("The PDF context cannot be empty.")

    prompt = f"""
You are NeuraDocs, an AI PDF Question Answering Assistant.

Answer the user's question using ONLY the supplied PDF context.

Rules:
1. Do not use outside knowledge.
2. Combine facts from multiple chunks when required.
3. Keep the answer clear and concise.
4. If the answer is unavailable in the context, reply exactly:
   "I could not find this information in the uploaded PDF."

PDF Context:
{context}

User Question:
{question}

Answer:
"""

    try:
        answer = generate_content(prompt)

        if not answer or not answer.strip():
            return (
                "No response was generated by the AI provider."
            )

        return answer.strip()

    except Exception as error:
        raise RuntimeError(
            f"Unable to generate an answer: {error}"
        ) from error